### ISSUE TITLE
Поддержка 2FA

### ISSUE THREAD

**Issue by SphereBread** [MarshalX/yandex-music-token#12]
У меня на аккаунте выключена авторизация по связке логин:пароль, подходит только **логин+одноразовый пароль**, либо **логин+QR** из приложения Яндекс.Ключ.

Если есть возможность -- добавь, пожалуйста, генерацию токена по одноразовому паролю.

**Comment by MarshalX** [comment]
Вход по одноразовому паролю работает. Есть несколько человек, кто успешно вошёл в свой аккаунт.

**Comment by SphereBread** [comment]
И правда :) Видимо, у меня руки кривые, сегодня всё с первого раза получилось.

Спасибо!
