### ISSUE TITLE
Не работает получение токена

### ISSUE THREAD

**Issue by old-man-lib** [MarshalX/yandex-music-token#21]
Привет, я сейчас увлекся Yandex API и пытаюсь написать более элегантный способ получения токена для Yandex Music, как только что то получится, сразу залью на GitHub.

**Comment by L11R** [comment]
@old-man-lib нужно юзать обычный Authorization Code flow. За базу взять можно [AppAuth-js](https://github.com/openid/AppAuth-JS).
